### ISSUE TITLE
Layout/xml for Game over screen

### ISSUE THREAD

**Issue by ImagineWagons8487** [ImagineWagons8487/FlailsAndFriends#23]

**Comment by dalibug** [comment]
Implement GameOverActivity with layout & logic
added:
GameOverActivity.java
activity_game_over.xml
updated: activity_landing_page.xml
Layout Changes:
Updated the activity_game_over.xml file to include:
A background image for the Game Over screen (game_over.png).
Custom-designed Retry and Quit buttons with updated styling and placement at the bottom of the screen.
Added Images:
Added new drawable resources:
retry_button.png: Custom image for the Retry button.
quit_button.png: Custom image for the Quit button.
Functional Placement:
Buttons are now aligned at the bottom of the screen to enhance user experience.
The Game Over text has been replaced by the background image text for better visual integration.
